/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IL1Read,
  IL1ReadInterface,
} from "../../../contracts/TriggerContract.sol/IL1Read";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "index",
        type: "uint32",
      },
    ],
    name: "oraclePx",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "index",
        type: "uint32",
      },
    ],
    name: "spotOraclePx",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL1Read__factory {
  static readonly abi = _abi;
  static createInterface(): IL1ReadInterface {
    return new Interface(_abi) as IL1ReadInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IL1Read {
    return new Contract(address, _abi, runner) as unknown as IL1Read;
  }
}
