/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BridgeHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "bridgeHype"
      | "bridgeToken"
      | "configureToken"
      | "getSystemAddress"
      | "getTokenConfig"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "tokenAddresses"
      | "tokenIndices"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgedToHyperCore"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "TokenConfigured"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeHype",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureToken",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSystemAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfig",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddresses",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIndices",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridgeHype", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSystemAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BridgedToHyperCoreEvent {
  export type InputTuple = [
    user: AddressLike,
    token: string,
    amount: BigNumberish,
    systemAddress: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    amount: bigint,
    systemAddress: string
  ];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
    systemAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenConfiguredEvent {
  export type InputTuple = [
    symbol: string,
    tokenAddress: AddressLike,
    tokenIndex: BigNumberish
  ];
  export type OutputTuple = [
    symbol: string,
    tokenAddress: string,
    tokenIndex: bigint
  ];
  export interface OutputObject {
    symbol: string;
    tokenAddress: string;
    tokenIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeHelper extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeHelper;
  waitForDeployment(): Promise<this>;

  interface: BridgeHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  bridgeHype: TypedContractMethod<[], [void], "payable">;

  bridgeToken: TypedContractMethod<
    [symbol: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  configureToken: TypedContractMethod<
    [symbol: string, tokenAddress: AddressLike, tokenIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSystemAddress: TypedContractMethod<
    [tokenIndex: BigNumberish],
    [string],
    "view"
  >;

  getTokenConfig: TypedContractMethod<
    [symbol: string],
    [
      [string, bigint, string] & {
        tokenAddress: string;
        tokenIndex: bigint;
        systemAddress: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tokenAddresses: TypedContractMethod<[arg0: string], [string], "view">;

  tokenIndices: TypedContractMethod<[arg0: string], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridgeHype"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "bridgeToken"
  ): TypedContractMethod<
    [symbol: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureToken"
  ): TypedContractMethod<
    [symbol: string, tokenAddress: AddressLike, tokenIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSystemAddress"
  ): TypedContractMethod<[tokenIndex: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenConfig"
  ): TypedContractMethod<
    [symbol: string],
    [
      [string, bigint, string] & {
        tokenAddress: string;
        tokenIndex: bigint;
        systemAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenAddresses"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "tokenIndices"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BridgedToHyperCore"
  ): TypedContractEvent<
    BridgedToHyperCoreEvent.InputTuple,
    BridgedToHyperCoreEvent.OutputTuple,
    BridgedToHyperCoreEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenConfigured"
  ): TypedContractEvent<
    TokenConfiguredEvent.InputTuple,
    TokenConfiguredEvent.OutputTuple,
    TokenConfiguredEvent.OutputObject
  >;

  filters: {
    "BridgedToHyperCore(address,string,uint256,address)": TypedContractEvent<
      BridgedToHyperCoreEvent.InputTuple,
      BridgedToHyperCoreEvent.OutputTuple,
      BridgedToHyperCoreEvent.OutputObject
    >;
    BridgedToHyperCore: TypedContractEvent<
      BridgedToHyperCoreEvent.InputTuple,
      BridgedToHyperCoreEvent.OutputTuple,
      BridgedToHyperCoreEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenConfigured(string,address,uint64)": TypedContractEvent<
      TokenConfiguredEvent.InputTuple,
      TokenConfiguredEvent.OutputTuple,
      TokenConfiguredEvent.OutputObject
    >;
    TokenConfigured: TypedContractEvent<
      TokenConfiguredEvent.InputTuple,
      TokenConfiguredEvent.OutputTuple,
      TokenConfiguredEvent.OutputObject
    >;
  };
}
