/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SwapContract {
  export type SwapRequestStruct = {
    user: AddressLike;
    fromToken: BigNumberish;
    toToken: BigNumberish;
    fromAmount: BigNumberish;
    minOutputAmount: BigNumberish;
    slippageBps: BigNumberish;
    timestamp: BigNumberish;
    completed: boolean;
    status: BigNumberish;
    fromTokenAddress: AddressLike;
  };

  export type SwapRequestStructOutput = [
    user: string,
    fromToken: bigint,
    toToken: bigint,
    fromAmount: bigint,
    minOutputAmount: bigint,
    slippageBps: bigint,
    timestamp: bigint,
    completed: boolean,
    status: bigint,
    fromTokenAddress: string
  ] & {
    user: string;
    fromToken: bigint;
    toToken: bigint;
    fromAmount: bigint;
    minOutputAmount: bigint;
    slippageBps: bigint;
    timestamp: bigint;
    completed: boolean;
    status: bigint;
    fromTokenAddress: string;
  };
}

export interface SwapContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "MAX_SLIPPAGE"
      | "completeSwap"
      | "emergencyWithdraw"
      | "executeSwap"
      | "getOraclePrice"
      | "getRoleAdmin"
      | "getSpotBalance"
      | "getSwap"
      | "getTokenSystemAddress"
      | "getUserSwaps"
      | "grantRole"
      | "hasRole"
      | "isRefundable"
      | "markSwapFailed"
      | "nextSwapId"
      | "pause"
      | "paused"
      | "renounceRole"
      | "requestRefund"
      | "revokeRole"
      | "sendHypeToSystem"
      | "supportsInterface"
      | "swapFee"
      | "swapRequests"
      | "swapTimeout"
      | "unpause"
      | "updateSwapFee"
      | "updateSwapTimeout"
      | "userSwaps"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "HypeSystemTransfer"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SwapCompleted"
      | "SwapFailed"
      | "SwapInitiated"
      | "SwapRefunded"
      | "SwapTimeoutUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SLIPPAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeSwap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSwap",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOraclePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenSystemAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSwaps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefundable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markSwapFailed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSwapId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendHypeToSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "swapFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateSwapFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSwapTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userSwaps",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLIPPAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOraclePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpotBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenSystemAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSwaps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markSwapFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextSwapId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendHypeToSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userSwaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HypeSystemTransferEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapCompletedEvent {
  export type InputTuple = [
    swapId: BigNumberish,
    user: AddressLike,
    outputAmount: BigNumberish
  ];
  export type OutputTuple = [
    swapId: bigint,
    user: string,
    outputAmount: bigint
  ];
  export interface OutputObject {
    swapId: bigint;
    user: string;
    outputAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapFailedEvent {
  export type InputTuple = [
    swapId: BigNumberish,
    user: AddressLike,
    reason: string
  ];
  export type OutputTuple = [swapId: bigint, user: string, reason: string];
  export interface OutputObject {
    swapId: bigint;
    user: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapInitiatedEvent {
  export type InputTuple = [
    swapId: BigNumberish,
    user: AddressLike,
    fromToken: BigNumberish,
    toToken: BigNumberish,
    fromAmount: BigNumberish,
    minOutputAmount: BigNumberish
  ];
  export type OutputTuple = [
    swapId: bigint,
    user: string,
    fromToken: bigint,
    toToken: bigint,
    fromAmount: bigint,
    minOutputAmount: bigint
  ];
  export interface OutputObject {
    swapId: bigint;
    user: string;
    fromToken: bigint;
    toToken: bigint;
    fromAmount: bigint;
    minOutputAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapRefundedEvent {
  export type InputTuple = [
    swapId: BigNumberish,
    user: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    swapId: bigint,
    user: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    swapId: bigint;
    user: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapTimeoutUpdatedEvent {
  export type InputTuple = [newTimeout: BigNumberish];
  export type OutputTuple = [newTimeout: bigint];
  export interface OutputObject {
    newTimeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapContract extends BaseContract {
  connect(runner?: ContractRunner | null): SwapContract;
  waitForDeployment(): Promise<this>;

  interface: SwapContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_SLIPPAGE: TypedContractMethod<[], [bigint], "view">;

  completeSwap: TypedContractMethod<
    [swapId: BigNumberish, outputAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeSwap: TypedContractMethod<
    [
      fromToken: BigNumberish,
      toToken: BigNumberish,
      fromAmount: BigNumberish,
      minOutputAmount: BigNumberish,
      slippageBps: BigNumberish,
      fromTokenAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;

  getOraclePrice: TypedContractMethod<
    [oracleIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSpotBalance: TypedContractMethod<
    [user: AddressLike, token: BigNumberish],
    [bigint],
    "view"
  >;

  getSwap: TypedContractMethod<
    [swapId: BigNumberish],
    [SwapContract.SwapRequestStructOutput],
    "view"
  >;

  getTokenSystemAddress: TypedContractMethod<
    [tokenIndex: BigNumberish],
    [string],
    "view"
  >;

  getUserSwaps: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isRefundable: TypedContractMethod<
    [swapId: BigNumberish],
    [[boolean, string] & { eligible: boolean; reason: string }],
    "view"
  >;

  markSwapFailed: TypedContractMethod<
    [swapId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  nextSwapId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRefund: TypedContractMethod<
    [swapId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sendHypeToSystem: TypedContractMethod<[], [void], "payable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  swapFee: TypedContractMethod<[], [bigint], "view">;

  swapRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        user: string;
        fromToken: bigint;
        toToken: bigint;
        fromAmount: bigint;
        minOutputAmount: bigint;
        slippageBps: bigint;
        timestamp: bigint;
        completed: boolean;
        status: bigint;
        fromTokenAddress: string;
      }
    ],
    "view"
  >;

  swapTimeout: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateSwapFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSwapTimeout: TypedContractMethod<
    [newTimeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  userSwaps: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SLIPPAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "completeSwap"
  ): TypedContractMethod<
    [swapId: BigNumberish, outputAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSwap"
  ): TypedContractMethod<
    [
      fromToken: BigNumberish,
      toToken: BigNumberish,
      fromAmount: BigNumberish,
      minOutputAmount: BigNumberish,
      slippageBps: BigNumberish,
      fromTokenAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getOraclePrice"
  ): TypedContractMethod<[oracleIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSpotBalance"
  ): TypedContractMethod<
    [user: AddressLike, token: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwap"
  ): TypedContractMethod<
    [swapId: BigNumberish],
    [SwapContract.SwapRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenSystemAddress"
  ): TypedContractMethod<[tokenIndex: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getUserSwaps"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRefundable"
  ): TypedContractMethod<
    [swapId: BigNumberish],
    [[boolean, string] & { eligible: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "markSwapFailed"
  ): TypedContractMethod<
    [swapId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextSwapId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[swapId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendHypeToSystem"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        user: string;
        fromToken: bigint;
        toToken: bigint;
        fromAmount: bigint;
        minOutputAmount: bigint;
        slippageBps: bigint;
        timestamp: bigint;
        completed: boolean;
        status: bigint;
        fromTokenAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "swapTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSwapFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSwapTimeout"
  ): TypedContractMethod<[newTimeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSwaps"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HypeSystemTransfer"
  ): TypedContractEvent<
    HypeSystemTransferEvent.InputTuple,
    HypeSystemTransferEvent.OutputTuple,
    HypeSystemTransferEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SwapCompleted"
  ): TypedContractEvent<
    SwapCompletedEvent.InputTuple,
    SwapCompletedEvent.OutputTuple,
    SwapCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SwapFailed"
  ): TypedContractEvent<
    SwapFailedEvent.InputTuple,
    SwapFailedEvent.OutputTuple,
    SwapFailedEvent.OutputObject
  >;
  getEvent(
    key: "SwapInitiated"
  ): TypedContractEvent<
    SwapInitiatedEvent.InputTuple,
    SwapInitiatedEvent.OutputTuple,
    SwapInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapRefunded"
  ): TypedContractEvent<
    SwapRefundedEvent.InputTuple,
    SwapRefundedEvent.OutputTuple,
    SwapRefundedEvent.OutputObject
  >;
  getEvent(
    key: "SwapTimeoutUpdated"
  ): TypedContractEvent<
    SwapTimeoutUpdatedEvent.InputTuple,
    SwapTimeoutUpdatedEvent.OutputTuple,
    SwapTimeoutUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "HypeSystemTransfer(address,uint256)": TypedContractEvent<
      HypeSystemTransferEvent.InputTuple,
      HypeSystemTransferEvent.OutputTuple,
      HypeSystemTransferEvent.OutputObject
    >;
    HypeSystemTransfer: TypedContractEvent<
      HypeSystemTransferEvent.InputTuple,
      HypeSystemTransferEvent.OutputTuple,
      HypeSystemTransferEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SwapCompleted(uint256,address,uint256)": TypedContractEvent<
      SwapCompletedEvent.InputTuple,
      SwapCompletedEvent.OutputTuple,
      SwapCompletedEvent.OutputObject
    >;
    SwapCompleted: TypedContractEvent<
      SwapCompletedEvent.InputTuple,
      SwapCompletedEvent.OutputTuple,
      SwapCompletedEvent.OutputObject
    >;

    "SwapFailed(uint256,address,string)": TypedContractEvent<
      SwapFailedEvent.InputTuple,
      SwapFailedEvent.OutputTuple,
      SwapFailedEvent.OutputObject
    >;
    SwapFailed: TypedContractEvent<
      SwapFailedEvent.InputTuple,
      SwapFailedEvent.OutputTuple,
      SwapFailedEvent.OutputObject
    >;

    "SwapInitiated(uint256,address,uint64,uint64,uint256,uint256)": TypedContractEvent<
      SwapInitiatedEvent.InputTuple,
      SwapInitiatedEvent.OutputTuple,
      SwapInitiatedEvent.OutputObject
    >;
    SwapInitiated: TypedContractEvent<
      SwapInitiatedEvent.InputTuple,
      SwapInitiatedEvent.OutputTuple,
      SwapInitiatedEvent.OutputObject
    >;

    "SwapRefunded(uint256,address,uint256)": TypedContractEvent<
      SwapRefundedEvent.InputTuple,
      SwapRefundedEvent.OutputTuple,
      SwapRefundedEvent.OutputObject
    >;
    SwapRefunded: TypedContractEvent<
      SwapRefundedEvent.InputTuple,
      SwapRefundedEvent.OutputTuple,
      SwapRefundedEvent.OutputObject
    >;

    "SwapTimeoutUpdated(uint256)": TypedContractEvent<
      SwapTimeoutUpdatedEvent.InputTuple,
      SwapTimeoutUpdatedEvent.OutputTuple,
      SwapTimeoutUpdatedEvent.OutputObject
    >;
    SwapTimeoutUpdated: TypedContractEvent<
      SwapTimeoutUpdatedEvent.InputTuple,
      SwapTimeoutUpdatedEvent.OutputTuple,
      SwapTimeoutUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
