/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TriggerContract {
  export type TriggerStruct = {
    id: BigNumberish;
    user: AddressLike;
    watchAsset: string;
    targetPrice: BigNumberish;
    isAbove: boolean;
    tradeAsset: string;
    isBuy: boolean;
    amount: BigNumberish;
    maxSlippage: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    status: BigNumberish;
    feePaid: BigNumberish;
    executedAt: BigNumberish;
    executionPrice: BigNumberish;
    executionTxHash: BytesLike;
  };

  export type TriggerStructOutput = [
    id: bigint,
    user: string,
    watchAsset: string,
    targetPrice: bigint,
    isAbove: boolean,
    tradeAsset: string,
    isBuy: boolean,
    amount: bigint,
    maxSlippage: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    status: bigint,
    feePaid: bigint,
    executedAt: bigint,
    executionPrice: bigint,
    executionTxHash: string
  ] & {
    id: bigint;
    user: string;
    watchAsset: string;
    targetPrice: bigint;
    isAbove: boolean;
    tradeAsset: string;
    isBuy: boolean;
    amount: bigint;
    maxSlippage: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    status: bigint;
    feePaid: bigint;
    executedAt: bigint;
    executionPrice: bigint;
    executionTxHash: string;
  };
}

export interface TriggerContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "MAX_TRIGGER_DURATION"
      | "MIN_TRIGGER_DURATION"
      | "activeTriggerCount"
      | "cancelTrigger"
      | "checkTrigger"
      | "createTrigger"
      | "getActiveTriggerCount"
      | "getRoleAdmin"
      | "getTrigger"
      | "getUserActiveTriggers"
      | "getUserTriggers"
      | "grantRole"
      | "hasRole"
      | "markExecuted"
      | "markExpired"
      | "markFailed"
      | "nextTriggerId"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "triggerFee"
      | "triggers"
      | "unpause"
      | "updateTriggerFee"
      | "userTriggers"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeUpdated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TriggerCancelled"
      | "TriggerCreated"
      | "TriggerExecuted"
      | "TriggerExpired"
      | "TriggerFailed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TRIGGER_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TRIGGER_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeTriggerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTrigger",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTrigger",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrigger",
    values: [
      string,
      BigNumberish,
      boolean,
      string,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveTriggerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrigger",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActiveTriggers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTriggers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExecuted",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExpired",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "markFailed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTriggerId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTriggerFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTriggers",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TRIGGER_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TRIGGER_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeTriggerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveTriggerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrigger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserActiveTriggers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTriggers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markFailed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTriggerId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "triggerFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "triggers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTriggerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTriggers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerCancelledEvent {
  export type InputTuple = [triggerId: BigNumberish, user: AddressLike];
  export type OutputTuple = [triggerId: bigint, user: string];
  export interface OutputObject {
    triggerId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerCreatedEvent {
  export type InputTuple = [
    triggerId: BigNumberish,
    user: AddressLike,
    watchAsset: string,
    targetPrice: BigNumberish,
    isAbove: boolean,
    tradeAsset: string,
    isBuy: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    triggerId: bigint,
    user: string,
    watchAsset: string,
    targetPrice: bigint,
    isAbove: boolean,
    tradeAsset: string,
    isBuy: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    triggerId: bigint;
    user: string;
    watchAsset: string;
    targetPrice: bigint;
    isAbove: boolean;
    tradeAsset: string;
    isBuy: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerExecutedEvent {
  export type InputTuple = [
    triggerId: BigNumberish,
    executor: AddressLike,
    executionPrice: BigNumberish,
    executionTxHash: BytesLike
  ];
  export type OutputTuple = [
    triggerId: bigint,
    executor: string,
    executionPrice: bigint,
    executionTxHash: string
  ];
  export interface OutputObject {
    triggerId: bigint;
    executor: string;
    executionPrice: bigint;
    executionTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerExpiredEvent {
  export type InputTuple = [triggerId: BigNumberish];
  export type OutputTuple = [triggerId: bigint];
  export interface OutputObject {
    triggerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerFailedEvent {
  export type InputTuple = [triggerId: BigNumberish, reason: string];
  export type OutputTuple = [triggerId: bigint, reason: string];
  export interface OutputObject {
    triggerId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TriggerContract extends BaseContract {
  connect(runner?: ContractRunner | null): TriggerContract;
  waitForDeployment(): Promise<this>;

  interface: TriggerContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_TRIGGER_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_TRIGGER_DURATION: TypedContractMethod<[], [bigint], "view">;

  activeTriggerCount: TypedContractMethod<[], [bigint], "view">;

  cancelTrigger: TypedContractMethod<
    [triggerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkTrigger: TypedContractMethod<
    [triggerId: BigNumberish, currentPrice: BigNumberish],
    [[boolean, string] & { shouldExecute: boolean; reason: string }],
    "view"
  >;

  createTrigger: TypedContractMethod<
    [
      watchAsset: string,
      targetPrice: BigNumberish,
      isAbove: boolean,
      tradeAsset: string,
      isBuy: boolean,
      amount: BigNumberish,
      maxSlippage: BigNumberish,
      durationHours: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getActiveTriggerCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTrigger: TypedContractMethod<
    [triggerId: BigNumberish],
    [TriggerContract.TriggerStructOutput],
    "view"
  >;

  getUserActiveTriggers: TypedContractMethod<
    [user: AddressLike],
    [TriggerContract.TriggerStructOutput[]],
    "view"
  >;

  getUserTriggers: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  markExecuted: TypedContractMethod<
    [
      triggerId: BigNumberish,
      executionPrice: BigNumberish,
      executionTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  markExpired: TypedContractMethod<
    [triggerIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  markFailed: TypedContractMethod<
    [triggerId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  nextTriggerId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  triggerFee: TypedContractMethod<[], [bigint], "view">;

  triggers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        user: string;
        watchAsset: string;
        targetPrice: bigint;
        isAbove: boolean;
        tradeAsset: string;
        isBuy: boolean;
        amount: bigint;
        maxSlippage: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
        feePaid: bigint;
        executedAt: bigint;
        executionPrice: bigint;
        executionTxHash: string;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTriggerFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  userTriggers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_TRIGGER_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TRIGGER_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeTriggerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelTrigger"
  ): TypedContractMethod<[triggerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkTrigger"
  ): TypedContractMethod<
    [triggerId: BigNumberish, currentPrice: BigNumberish],
    [[boolean, string] & { shouldExecute: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createTrigger"
  ): TypedContractMethod<
    [
      watchAsset: string,
      targetPrice: BigNumberish,
      isAbove: boolean,
      tradeAsset: string,
      isBuy: boolean,
      amount: BigNumberish,
      maxSlippage: BigNumberish,
      durationHours: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getActiveTriggerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTrigger"
  ): TypedContractMethod<
    [triggerId: BigNumberish],
    [TriggerContract.TriggerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActiveTriggers"
  ): TypedContractMethod<
    [user: AddressLike],
    [TriggerContract.TriggerStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTriggers"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markExecuted"
  ): TypedContractMethod<
    [
      triggerId: BigNumberish,
      executionPrice: BigNumberish,
      executionTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markExpired"
  ): TypedContractMethod<[triggerIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markFailed"
  ): TypedContractMethod<
    [triggerId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTriggerId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "triggerFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "triggers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        user: string;
        watchAsset: string;
        targetPrice: bigint;
        isAbove: boolean;
        tradeAsset: string;
        isBuy: boolean;
        amount: bigint;
        maxSlippage: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
        feePaid: bigint;
        executedAt: bigint;
        executionPrice: bigint;
        executionTxHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTriggerFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userTriggers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerCancelled"
  ): TypedContractEvent<
    TriggerCancelledEvent.InputTuple,
    TriggerCancelledEvent.OutputTuple,
    TriggerCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TriggerCreated"
  ): TypedContractEvent<
    TriggerCreatedEvent.InputTuple,
    TriggerCreatedEvent.OutputTuple,
    TriggerCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerExecuted"
  ): TypedContractEvent<
    TriggerExecutedEvent.InputTuple,
    TriggerExecutedEvent.OutputTuple,
    TriggerExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerExpired"
  ): TypedContractEvent<
    TriggerExpiredEvent.InputTuple,
    TriggerExpiredEvent.OutputTuple,
    TriggerExpiredEvent.OutputObject
  >;
  getEvent(
    key: "TriggerFailed"
  ): TypedContractEvent<
    TriggerFailedEvent.InputTuple,
    TriggerFailedEvent.OutputTuple,
    TriggerFailedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TriggerCancelled(uint256,address)": TypedContractEvent<
      TriggerCancelledEvent.InputTuple,
      TriggerCancelledEvent.OutputTuple,
      TriggerCancelledEvent.OutputObject
    >;
    TriggerCancelled: TypedContractEvent<
      TriggerCancelledEvent.InputTuple,
      TriggerCancelledEvent.OutputTuple,
      TriggerCancelledEvent.OutputObject
    >;

    "TriggerCreated(uint256,address,string,uint256,bool,string,bool,uint256)": TypedContractEvent<
      TriggerCreatedEvent.InputTuple,
      TriggerCreatedEvent.OutputTuple,
      TriggerCreatedEvent.OutputObject
    >;
    TriggerCreated: TypedContractEvent<
      TriggerCreatedEvent.InputTuple,
      TriggerCreatedEvent.OutputTuple,
      TriggerCreatedEvent.OutputObject
    >;

    "TriggerExecuted(uint256,address,uint256,bytes32)": TypedContractEvent<
      TriggerExecutedEvent.InputTuple,
      TriggerExecutedEvent.OutputTuple,
      TriggerExecutedEvent.OutputObject
    >;
    TriggerExecuted: TypedContractEvent<
      TriggerExecutedEvent.InputTuple,
      TriggerExecutedEvent.OutputTuple,
      TriggerExecutedEvent.OutputObject
    >;

    "TriggerExpired(uint256)": TypedContractEvent<
      TriggerExpiredEvent.InputTuple,
      TriggerExpiredEvent.OutputTuple,
      TriggerExpiredEvent.OutputObject
    >;
    TriggerExpired: TypedContractEvent<
      TriggerExpiredEvent.InputTuple,
      TriggerExpiredEvent.OutputTuple,
      TriggerExpiredEvent.OutputObject
    >;

    "TriggerFailed(uint256,string)": TypedContractEvent<
      TriggerFailedEvent.InputTuple,
      TriggerFailedEvent.OutputTuple,
      TriggerFailedEvent.OutputObject
    >;
    TriggerFailed: TypedContractEvent<
      TriggerFailedEvent.InputTuple,
      TriggerFailedEvent.OutputTuple,
      TriggerFailedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
